"""made changes to product_user table

Revision ID: 7b1cd0fd83ee
Revises: f715d5c3f8be
Create Date: 2023-06-07 17:20:03.738879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1cd0fd83ee'
down_revision = 'f715d5c3f8be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_users', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_users', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
