"""added price column to product table

Revision ID: f715d5c3f8be
Revises: 663ddfdf7c6b
Create Date: 2023-06-07 17:00:44.940190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f715d5c3f8be'
down_revision = '663ddfdf7c6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
